package com.example.cp.licenses;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Wraps a signed JWT in the .lic envelope JSON contract that customers' Docker apps consume.
 */
@Component
public class LicenseFileBuilder {

    private final ObjectMapper objectMapper;
    private final String issuer;

    public LicenseFileBuilder(ObjectMapper objectMapper,
                              @Value("${app.signing.issuer}") String issuer) {
        this.objectMapper = objectMapper;
        this.issuer = issuer;
    }

    public byte[] buildEnvelopeBytes(LicenseIssuer.IssuedLicense issued, String notesOverride) {
        Map<String, Object> envelope = new LinkedHashMap<>();
        envelope.put("license", issued.jwt());
        envelope.put("issued_at", DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(issued.issuedAt()));
        envelope.put("customer", issued.orgName());
        envelope.put("plan", issued.planCode());
        envelope.put("expires_at", DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(issued.expiresAt()));
        envelope.put("notes", notesOverride != null && !notesOverride.isBlank()
                ? notesOverride
                : "Generated by " + issuer + ". Drop this file at /etc/app/license.lic.");
        try {
            return objectMapper.writerWithDefaultPrettyPrinter()
                    .writeValueAsBytes(envelope);
        } catch (JsonProcessingException e) {
            throw new RuntimeException("Failed to build .lic envelope", e);
        }
    }

    public String suggestedFilename(LicenseIssuer.IssuedLicense issued) {
        String slug = issued.orgSlug() == null ? "license" : issued.orgSlug();
        String shortJti = issued.jti();
        if (shortJti.startsWith("lic_") && shortJti.length() > 12) {
            shortJti = shortJti.substring(4, 12);
        }
        return slug + "-" + shortJti + ".lic";
    }

    @SuppressWarnings("unused")
    private static byte[] utf8(String s) {
        return s.getBytes(StandardCharsets.UTF_8);
    }
}
